name: "Main CI"

on:
  push:
    branches:
      - main

jobs:
  cancel-previous:
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  build:
    needs: cancel-previous
    uses: ./.github/workflows/job-build.yaml

  test:
    needs: build
    uses: ./.github/workflows/job-test.yaml

  deploy:
    needs: test
    uses: ./.github/workflows/job-deploy.yaml
