name: "Deploy"

on:
  workflow_call:
    inputs:
      API_CONTAINER_URL:
        required: true
        type: string
      ADVISORY_CONTAINER_URL:
        required: true
        type: string
      TASK_RUNNER_CONTAINER_URL:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: "https://google.com/"
    steps:
      - name: Deploy
        run: |
          echo Deploy ${{ inputs.API_CONTAINER_URL }}
          echo Deploy ${{ inputs.ADVISORY_CONTAINER_URL }}
          echo Deploy ${{ inputs.TASK_RUNNER_CONTAINER_URL }}
