name: "Build"

on:
  workflow_call:
    inputs:
      MATRIX:
        required: true
        type: string

    outputs:
      OVERLAY:
        description: "OVERLAY"
        value: ${{jobs.build-docker.outputs.OVERLAY}}

jobs:
  build-docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        OVERLAY: ${{inputs.MATRIX}}
    outputs:
      OVERLAY: ${{steps.out.outputs.OVERLAY}}

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Print
        run: echo "${{matrix.OVERLAY}}"

      - name: Output
        id: out
        run: echo "::set-output name=OVERLAY::${{matrix.OVERLAY}}"
