name: "Deploy"

on:
  workflow_call:

jobs:
  deploy_staging:
    if: secrets.ENV == 'staging'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          echo "Deploy staging"
          ls -lah

  deploy_production:
    if: secrets.ENV == 'production'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          echo "Deploy production"
          ls -lah
