name: "Test"

on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Test
        run: yarn test --coverage

      - name: Archive coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: |
            coverage
