name: "Deploy"

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: "https://google.com/"
    steps:
      - name: Create GitHub release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
        env:
          GITHUB_TOKEN: ${{github.token}}
        with:
          generate_release_notes: true

      - name: Deploy
        run: |
          echo Deploy ${{ secrets.ENV }}
          ls -lah
