name: "Deploy"

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: "https://google.com/"
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build

      - name: Deploy
        run: |
          echo Deploy ${{ secrets.ENV }}
          ls -lah
