name: "Deploy"

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          echo "is staging ${{secrets.ENV == 'staging'}}"
          echo "is production ${{secrets.ENV == 'production'}}"
          ls -lah
