name: "Build"

on:
  workflow_call:
    inputs:
      APP:
        required: true
        type: string

    outputs:
      APP:
        description: "APP"
        value: ${{jobs.build-docker.outputs.APP}}

jobs:
  build-docker:
    runs-on: ubuntu-latest
    outputs:
      APP: ${{steps.out.outputs.APP}}

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Print
        run: echo "${{inputs.APP}}"

      - name: Output
        id: out
        run: echo "::set-output name=APP::${{inputs.APP}}"
