name: "Test types"

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact base-repo
        uses: actions/download-artifact@v2
        with:
          name: base-repo

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Test
        run: yarn test:types
