name: "Deploy"

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: "https://google.com/"
    steps:
      - name: Deploy
        run: |
          echo Deploy ${{ secrets.ENV }}
          ls -la
