name: "Build"

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact base-repo
        uses: actions/download-artifact@v2
        with:
          name: base-repo

      - name: Build
        run: yarn build
