name: "Push"

on:
  push:
    branches:
      - main

jobs:
  cancel-previous:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  build-a:
    needs: cancel-previous
    uses: ./.github/workflows/job-build-docker.yaml
    with:
      OVERLAY: a

  build-b:
    needs: cancel-previous
    uses: ./.github/workflows/job-build-docker.yaml
    with:
      OVERLAY: b

  build-c:
    needs: cancel-previous
    uses: ./.github/workflows/job-build-docker.yaml
    with:
      OVERLAY: c

  build:
    needs: [build-a, build-b, build-c]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build successful"

  test:
    needs: cancel-previous
    uses: ./.github/workflows/job-test.yaml

  deploy:
    needs: [build, test]
    uses: ./.github/workflows/job-deploy.yaml
