name: "Push"

on:
  push:
    branches:
      - main

jobs:
  cancel-previous:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  build-api:
    needs: cancel-previous
    uses: ./.github/workflows/job-build-docker.yaml
    with:
      APP: api

  build-advisory:
    needs: cancel-previous
    uses: ./.github/workflows/job-build-docker.yaml
    with:
      APP: advisory

  build-task-runner:
    needs: cancel-previous
    uses: ./.github/workflows/job-build-docker.yaml
    with:
      APP: task-runner

  print:
    needs: [build-api, build-advisory, build-task-runner]
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ needs }}"
      - run: echo "${{ needs.build-api.outputs }}"
      - run: echo "${{ needs.build-advisory.outputs }}"
      - run: echo "${{ needs.build-task-runner.outputs }}"

  test:
    needs: cancel-previous
    uses: ./.github/workflows/job-test.yaml

  deploy:
    needs: [build-api, build-advisory, build-task-runner, test]
    uses: ./.github/workflows/job-deploy.yaml
