name: "Push"

on:
  push:
    branches:
      - main

jobs:
  cancel-previous:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  build:
    needs: cancel-previous
    strategy:
      matrix:
        app: [api]
    uses: ./.github/workflows/job-build-docker.yaml
    with:
      OVERLAY: matrix.app

  print:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ toJson(needs.build.api.outputs) }}"
      - run: echo "${{ toJson(needs.build.advisory.outputs) }}"

  test:
    needs: cancel-previous
    uses: ./.github/workflows/job-test.yaml

  deploy:
    needs: [build, test]
    uses: ./.github/workflows/job-deploy.yaml
